### ISSUE TITLE
"Laggy" behaviour for bigger files

### ISSUE THREAD

**Issue by ceskyDJ** [adil192/saber#233] opened 2023-01-14 00:33 UTC
**Describe the bug**
When I write a little bigger note, it starts causing lags after some time. The best is just to see my video (I'm sorry for the pure English in it and for the length of the video but I think it is well presented there).

**To Reproduce**
1. Create new note
2. Write longer text
3. After some time of writing, lags come
4. After another time of writing, lags are so frequent, you just don't see what you are writing

**Expected behavior**
I need a smooth writing experience to use your app for more serious things (like school/work notes). The app is so good and actively developed, so I hope, you just fix this and it will be almost ready for "production" use.

**Screenshots**

https://user-images.githubusercontent.com/48548230/212441034-1e418167-c126-49e6-91c5-f0bc6eb84a04.mp4

**Device:**
 - Device: Samsung Galaxy Tab S8
 - OS: Android 13
 - Version: v0.5.5 (recorded on v0.5.4 but tried one more again at v0.5.5 and it is almost the same experience) - from Google Play

**Comment by ceskyDJ** [comment] 2023-01-14 00:40
I hope it is at least a bit visible from the video. In reality, it is a bit worse, I would say.

**Comment by Alenygam** [comment] 2023-01-14 17:22
I have the same issue on v0.5.5 from F-Droid on a Samsung Tab S6 Lite (2021). Also while it lags when I exit the app sometimes my whole note gets wiped and I lose my work 😔

**Comment by ceskyDJ** [comment] 2023-01-14 17:34
> I have the same issue on v0.5.5 from F-Droid on a Samsung Tab S6 Lite (2021). Also while it lags when I exit the app sometimes my whole note gets wiped and I lose my work pensive

Do you have set up NextCloud connection? In case of true, do you use custom server or default for the app?

**Comment by Alenygam** [comment] 2023-01-14 21:31
I do not have a Nextcloud connection set up.

**Comment by adil192** [comment] 2023-01-15 05:54
Duplicate of #179

**Comment by ceskyDJ** [comment] 2023-01-15 18:11
Oh, I'm sorry. I tried to found older issue but I wasn't successful.

**Closed** 2023-01-18 01:17 UTC
Labels: bug, duplicate
