### ISSUE TITLE
iPad PDF/PNG export endless spinning

### ISSUE THREAD

**Issue by theIuser** [adil192/saber#740] opened 2023-06-23 07:44 UTC
### Describe the bug

Whenever I try to export a note as pdf or png the iOS share dialog never shows up.
It works on iOS but not iPadOS.

### To reproduce

1. create new note and draw something
2. open share dialog from toolbar and start an export (PDF or PNG)
3. spinning arrow stops but the iPadOS share dialog never showed up

### Expected behavior

iPadOS share dialog to show up and give me an option to share this with external app

### Saber version

v0.13.1 (13010)

### Device

- Device: iPad Pro
- OS: 15.4.1 and 16.5

**Comment by hankertrix** [comment] 2024-02-04 15:31
I also face the same issue. However, the spinning arrow icon spins for a while (roughly 5 seconds), and freezes for a moment, like it's trying to open something, then it just continues spinning without opening the iPadOS share dialog.

Below are the relevant details:

### Saber version
v0.19.2 App Store (19020)

### Device
- iPad (7th generation)
- OS: iPadOS 17.3

**Comment by hankertrix** [comment] 2024-02-04 16:38
I have found the cause of the issue in [line 191 of file_manager.dart](https://github.com/saber-notes/saber/blob/main/lib/data/file_manager/file_manager.dart#L191).

There is no `sharePositionOrigin` parameter when calling the `shareXFiles` function of the `Share` class. The `share_plus` library requires the `sharePositionOrigin` parameter on iPads, as without it, `share_plus` will not work on iPads and will result in the UI not responding, which is what happens in this case. This requirement also applies to the `shareXFiles` function of the `Share` class.

Here is the `share_plus` library documentation talking about the issue (the issue is at the bottom of the page):
https://pub.dev/packages/share_plus#known-issues

Here is the `share_plus` library documentation for the `shareXFiles` function of the `Share` class:
https://pub.dev/documentation/share_plus/latest/share_plus/Share/shareXFiles.html

**Comment by RamsaKd** [comment] 2024-02-13 19:43
I have this same issue on various linux & android devices could it be the same cause?

**Comment by hankertrix** [comment] 2024-02-14 06:05
On Android and Linux I doubt that the lack of the `sharePositionOrigin` parameter is the cause, as the `share_plus` documentation doesn’t list any known issues for Android, and the Linux export is completely different from the Android and iOS version and doesn’t use the `share_plus` library.

Either way, this particular issue with iPad export seems to have been addressed in commit 1dd247630ee93dc41ee08e51013577b9be5d8471.

**Comment by hankertrix** [comment] 2024-02-14 06:14
After updating the Saber app on the iPad to the latest version, it seems like this issue has been addressed and exporting now works on iPads.

This issue can be closed.

**Closed as completed** 2024-02-14 21:09 UTC
Labels: bug
