### ISSUE TITLE
[Mobile] Add custom folder to save files

### ISSUE THREAD

**Issue by Luciogi** [adil192/saber#189] opened 2022-12-30 18:49 UTC
**Is your feature request related to a problem? Please describe.**
Application should allow custom folder for files. As for user who don't want to use cloud, can easily backup files using local syncing software (e.g Syncthing)

**Describe the solution you'd like**
Custom folder option in Application first start up , and also in app settings

**Describe alternatives you've considered**
I used NeoBackup app to backup who app data which uses root

**Device (please complete the following information):**
 - Device: Redmi 9t
 - OS: Android 13
 - Version: 0.5.1 Fdroid

**Additional context**
nope

**Comment by Luciogi** [comment] 2022-12-30 18:53
For now `.sbn` files are located at `/data_mirror/data_ce/null/0/com.adilhanney.saber/app_flutter/Saber` on android. Which requires root access to view or copy

**Comment by adil192** [comment] 2022-12-30 19:06
Duplicate of #24

**Closed** 2022-12-30 19:06 UTC
Labels: duplicate, enhancement

**Comment by Luciogi** [comment] 2022-12-30 19:20
Ops, I could not find that .
