### ISSUE TITLE
Awkward movement

### ISSUE THREAD

**Issue by PolarianDev** [adil192/saber#683] opened 2023-06-05 12:04 UTC
### Describe the bug

Using saber is very clunky at the moment, trying to move about doesn't work.

I am used to xournal++ and moving about is as simple as scrolling up and down on the trackpad. With saber however this motion doesn't work at all.

I also don't have zoom enabled on my trackpad and there is no button to zoom in and out, or if there is I do not see it within the menu when I have a notes page open.

This makes saber almost completely unusable.

### To reproduce

1. Open a note document
2. Attempt the motions described above

### Expected behavior

Scrolling up and down on the trackpad should work, otherwise it is awkward to use. scrolling up and down on the trackpad currently just draws and vertical line when the cursor is over the notepad, and when it is over the border, nothing happens.

Using a wacom tablet is awkward, pressing down the mouse (left click) works like expected, but the function keys on the pen (right click and middle click) also draw and it makes it so awkward to hold them pen becuase you cant touch them buttons or they will mess up your notes.

Only left mouse button should be able to draw, this should be configurable but I do not see any configuration setting for it.

zooming in and out is currently impossible. I have the logic disabled on my trackpad for easier navigation, but there is no button for zooming in and out.

### Saber version

0.12.9-1 (from AUR)

### Device

- Device: Thinkpad E14
- OS: Arch Linux

### Anything else?

N/A

**Comment by adil192** [comment] 2023-06-05 16:29
> I also don't have zoom enabled on my trackpad and there is no button to zoom in and out, or if there is I do not see it within the menu when I have a notes page open.

For now you can use `Ctrl +` and `Ctrl -` to zoom in and out on desktop. I do like the idea of having a plus and minus button on either side of the zoom indicator. Please can you file a feature request for this?

> This makes saber almost completely unusable.

Please refrain from superlatives like this.

**Comment by adil192** [comment] 2023-06-05 16:29
Other than that, I'll mark this as a duplicate of #178.

**Closed by adil192** 2023-06-05 16:29 UTC
Labels: bug, duplicate

**Comment by PolarianDev** [comment] 2023-06-05 23:21
> Please refrain from superlatives like this.
Completely useless for me*

That is not exaggerated, it is impossible to navigate saber therefore I can't really write notes xD

> Other than that, I'll mark this as a duplicate of https://github.com/adil192/saber/issues/178.
Ah I did not realise this already existed, sorry...
