### ISSUE TITLE
Pen not recognized as a "pen" in Windows

### ISSUE THREAD

**Issue by xx1182** [adil192/saber#855] opened 2023-07-27 18:45 UTC
### Describe the bug

When using the pen, it doesn't get recognized as a pen, thus not having sensitivity levels etc.
Can write with the pen, but only by choosing the button that allows you to draw with finger.
Nontheless the pen works(and gets recogninzed) in other apps such as OneNote and Whiteboard.

### To reproduce

1. Open the app
2. Get the Pen
3. Disable the "finger input"
4. Pen is regarded as a "mouse"

### Expected behavior

Oh wow a pen, must set myself accordingly to the windows sdk pen ink whatever, with aknowledgement that the pen may have buttons, and those buttons could be set wow this is great i love gettin writed on.

### Saber version

v0.14.11.0(14110)

### Device

Device: 
Nome dispositivo:	Astro_m
Penna e tocco: 	Supporto input penna e tocco con 10 punti tocco (Pen and touch: Support pen input with 10 touch points)[Copied from Windows INFO]
OS: W11

### Anything else?

Great App! A few missing features:
Would really love to hear a pencil on paper when drawing, otherwise great and responsive, but a little bit counter-intuitive/cluttered.
Regards.

**Comment by ceskyDJ** [comment] 2023-07-29 07:02
> but a little bit counter-intuitive/cluttered

Could you be more specific, please?

**Comment by xx1182** [comment] 2023-07-29 08:23
For starters, personally there should be an "on hover" that tells you what the buttons do, yeah even for the intuitive ones like the pen button, and when you pot the sidebar on the left/right, personally there should be only 1 scrollable column(the undo/redo/share button get another column)

And 
![Bttn](https://github.com/adil192/saber/assets/6748908/10d5c8e1-9ba3-4cfd-8d9c-14a5a35d8a68)

What does this button do? Nothing changes.
Regards.

**Comment by ceskyDJ** [comment] 2023-07-29 08:34
Thanks! Most of buttons have got a descriptive title, you can display it by holding your finger on the button.

**Comment by MrGumpIT** [comment] 2023-09-07 06:06
I have the same problem. In short, when using a graphic tablet connected to the pc, the input is not recognized because saber does not use windows ink, to make it work it is necessary to use the mouse mode of the graphic tablet but this implies the lack of functionality of the pressure recognition and the non-use of the pen buttons.

**Comment by ceskyDJ** [comment] 2023-09-07 10:50
Did you try https://github.com/flutter/flutter/issues/65248#issuecomment-1628041259?

**Comment by adil192** [comment] 2023-09-11 01:42
Duplicate of https://github.com/adil192/saber/issues/671

**Closed** 2023-09-11 01:42 UTC
Labels: bug
