### ISSUE TITLE
Writing becomes laggy in longer notes

### ISSUE THREAD

**Issue by m0byn** [adil192/saber#472] opened 2023-03-15 11:55 UTC
**Describe the bug**
I am using the S-Pen for taking notes on my Samsung Tablet. On new and empty notes, everything works very well and smoothly. Then, after writing some pages, i.e. no fresh notes but longer ones, writing becomes laggy and starts getting annoying at some point! Please see the two screen recordings below.

**To Reproduce**
1. Go to 'new note'
2. Write several pages
4. See how writing becomes more laggy

**Expected behavior**
No lagging as it is when opening a new note.

**Screenshots**
1. Lagging (longer notes):
https://user-images.githubusercontent.com/33026003/225301529-f93325b4-82e8-4a94-8f18-84f3d2b43ffe.mp4

3. Not lagging (new note):
https://user-images.githubusercontent.com/33026003/225301546-6fc4910d-8311-4252-8c28-20bd388ecb78.mp4

**Device (please complete the following information):**
 - Device: Samsung Galaxy Tab S4
 - OS: LineageOS 20 (Android 13)
 - Version: v0.9.8

I am happy to share any additional information necessary to solve the issue!

**Comment by WasteOfO2** [comment] 2023-03-15 13:32
I have noticed the same thing, I was planning on creating an issue but ig u did it first :p

I think this might have something to do with Saber perhaps not supporting Hardware Acceleration? Ram doesnt seem to be an issue.

![Screenshot_20230314-232836_Settings](https://user-images.githubusercontent.com/45941793/225317709-bee0fbb2-4553-435c-848b-84bb8726bee7.png)
![Screenshot_20230314-232828_Settings](https://user-images.githubusercontent.com/45941793/225317716-a71c9f61-95ef-4f5b-afc0-545c8baca07d.png)

Android does have support for this, not 100% sure about on Flutter.

[Android wiki for hardware acceleration](https://developer.android.com/topic/performance/hardware-accel)

[Flutter wiki for rendering performance](https://docs.flutter.dev/perf/rendering-performance)

To test my theory, I did the following:

1. Forced 4X MSAA in dev options --> Hardware Accelerated Rendering
2. Disbaled HW overlays (forces GPU to composite screens) in dev options --> Hardware Accelerated Rendering

Now, to check whether Saber actually uses hardware rendering, I did:

1. Show View Updates in dev options

This option starts flashing all the windows that use GPU rendering in red colour (See videos)

https://user-images.githubusercontent.com/45941793/225321541-78c539c1-1664-4366-9042-850b1f421061.mp4


https://user-images.githubusercontent.com/45941793/225321568-e1807f65-47a4-4b05-ad6e-bc1b4395db30.mp4

Note: The lag may be exaggerated as I am screen recording, to be as representable of the situation to the issue as possible, I did not enable pointer location.

For reference, I also compared with the browser to check whether this is Saber specific.

So with this I can actually conclude that Saber uses software rendering, which is not efficient.

Mobile devices are affected disproportionately, as they are lower power compared to desktop/laptop counterparts.

I cannot confirm this issue exists on desktop OS.

I am not 100% sure whether this is the actual culprit, but this is my best guess as for what actually be taking place.

**Comment by adil192** [comment] 2023-03-15 17:16
Closing as a duplicate of #179

**Closed by adil192** 2023-03-15 17:16 UTC
Labels: bug

**Comment by Iey4iej3** [comment] 2023-04-28 05:57
> I have noticed the same thing, I was planning on creating an issue but ig u did it first :p
> 
> I think this might have something to do with Saber perhaps not supporting Hardware Acceleration? Ram doesnt seem to be an issue.
> 
> ![Screenshot_20230314-232836_Settings](https://user-images.githubusercontent.com/45941793/225317709-bee0fbb2-4553-435c-848b-84bb8726bee7.png) ![Screenshot_20230314-232828_Settings](https://user-images.githubusercontent.com/45941793/225317716-a71c9f61-95ef-4f5b-afc0-545c8baca07d.png)
> 
> Notice how Saber doesn't use GPU

I tried the same for Quill (https://f-droid.org/en/packages/com.write.Quill/) but I do not even see memory usage of it (but I did not do a very long test). Is that using GPU?

**Comment by Iey4iej3** [comment] 2023-04-29 12:09
After a relatively heavy use of Quill, I now see it, and it does not use GPU either. Maybe the hardware acceleration is not the key to the sluggishness.
