### ISSUE TITLE
Deletion after selection

### ISSUE THREAD

**Issue by Luciogi** [adil192/saber#356] opened 2023-02-15 09:08 UTC
**Is your feature request related to a problem? Please describe.**
Delete selected object/stroke

**Describe the solution you'd like**
1. Select then press eraser -> delete object
2. Selection path show little(cross button ❌ ) -> delete object
   - This approach would need to tackle zoom in / out and cross button (❌)

**Describe alternatives you've considered**

**Device (please complete the following information):**
 - Device: Redmi 9T
 - OS: Android 13
 - Version: 0.8.0

**Additional context**

**Comment by adil192** [comment] 2023-02-15 17:59
I'm going to combine this into the older selection issue
- Duplicate of #170

**Closed by adil192** 2023-02-15 17:59 UTC
Labels: duplicate, enhancement
