### ISSUE TITLE
S-Pen testing and unrelated bug report

### ISSUE THREAD

**Issue by nicoleritzer** [adil192/saber#21] opened 2022-09-24 19:31 UTC
Hi! Thanks for developing Saber, I like it a lot, especially as an alternative to S-Notes, etc.

I've tested the "erase" function with my S-Pen (Samsung Galaxy Note 10+, Snapdragon); the app crashes when the button is pressed and the stylus touches the screen.

Also, an unrelated bug:
1. I zoom in on the canvas
2. Draw something
3. Zoom out
4. Draw something else

The mark drawn in step 2 will disappear when another mark is made in step 4. This occurs whether zooming in, then out, or out －> in.

Thank you, I hope this makes sense.

**Comment by adil192** [comment] 2022-09-24 19:42
> I've tested the "erase" function with my S-Pen (Samsung Galaxy Note 10+, Snapdragon); the app crashes when the button is pressed and the stylus touches the screen.

Yes I've just encountered this bug today! It seems like the crash is up to Flutter to fix as it throws an error when an unknown button (the S Pen button) is pressed https://github.com/flutter/flutter/issues/111068. Unfortunately I can't do much about this.

> Also, an unrelated bug:
> 
>     1. I zoom in on the canvas
> 
>     2. Draw something
> 
>     3. Zoom out
> 
>     4. Draw something else
> 
> 
> The mark drawn in step 2 will disappear when another mark is made in step 4. This occurs whether zooming in, then out, or out －> in.

Thanks for the report, I hadn't seen this before. I can't seem to reproduce this behaviour on my end. Can I ask whether you're releasing your finger after drawing before zooming? If you draw something with one finger, add a finger to zoom, then the app will think your first stroke was a mistake.

**Comment by nicoleritzer** [comment] 2022-09-24 20:12
I've attached a screen recording to hopefully give you a better idea; keeping the zoom gesture and the drawing gesture deliberately separate to avoid accidentally doing what you described.

https://user-images.githubusercontent.com/42187709/192116637-48f6a6b6-cb01-4267-b52b-3f0892c4db4b.mp4

**Comment by adil192** [comment] 2022-09-24 20:35
Turns out this only happens when using a stylus to draw. I'll need to look into this some more

**Comment by adil192** [comment] 2022-09-29 19:49
Hi @nicoleritzer, please can you check if the disappearing strokes issue is fixed with [v0.3.9](https://github.com/adil192/saber/releases/tag/v0.3.9)

**Comment by nicoleritzer** [comment] 2022-09-30 16:47
It's fixed, no more disappearing strokes. Thank you for your hard work!

**Closed** 2022-09-30 17:35 UTC
Labels: bug
