### ISSUE TITLE
Support for generic webdav filesystem

### ISSUE THREAD

**Issue by PolarianDev** [adil192/saber#906] opened 2023-08-30 11:35 UTC
### Motivation

Currently saber only supports Nextcloud.

Nextcloud uses webdav for its filesystem.

Any generic webdav could easily be supported if an option is set to set the username and password, this is then base64 encoded according to the basic auth specification, this will allow easy compatibility with any generic webdav filesystem, which allows for people to host lightweight file servers with nginx for example, without needing to spin up a full on nextcloud instance.

### Solution

See above.

### Saber version

0.15.3

### Device

N/A

**Comment by adil192** [comment] 2023-08-30 21:43
Duplicate of https://github.com/adil192/saber/issues/201

**Closed by adil192** 2023-08-30 21:43 UTC
Labels: enhancement

**Comment by PolarianDev** [comment] 2023-08-30 22:17
Apologies for the duplicate.

**Comment by adil192** [comment] 2023-08-31 16:18
No worries
