### ISSUE TITLE
Change colors of selected object

### ISSUE THREAD

**Issue by Luciogi** [adil192/saber#357] opened 2023-02-15 09:18 UTC
**Is your feature request related to a problem? Please describe.**
_same as title_

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Device (please complete the following information):**
 - Device: Redmi 9T
 - OS:  Android 13
 - Version: 0.8.0 F-droid

**Additional context**

**Comment by adil192** [comment] 2023-02-15 17:59
I'm going to combine this into the older selection issue
- Duplicate of #170

**Closed by adil192** 2023-02-15 17:59 UTC
Labels: duplicate, enhancement
