### ISSUE TITLE
Two finger detection need improvement 

### ISSUE THREAD

**Issue by Luciogi** [adil192/saber#192] opened 2022-12-31 13:51 UTC
**Describe the bug**
As navigation is done by 2 finger gesture, it works but leave dots specially with pen. Lets say moving with eraser it might remove object

**To Reproduce**
1. Toggle Finger Drawing mode
2. Select pen
3. Zoom in 
4. Then Use two finger to navigate on page
5. You will be dot will be created on page

**Expected behavior**
Tools should not working during navigation on zoomed page

**Screenshots**

https://user-images.githubusercontent.com/84625092/210138829-99238edb-cf28-46ab-a649-5f5b15124585.mp4

**Device (please complete the following information):**
 - Device: Redmi 9t
 - OS: Android 13
 - Version: 0.5.2
 - Browser (if applicable):

**Comment by adil192** [comment] 2022-12-31 14:10
Duplicate of #38

**Closed** 2022-12-31 14:11 UTC
Labels: bug, duplicate
