### ISSUE TITLE
Login into Nextcloud instance without encryption

### ISSUE THREAD

**Issue by pes4murai** [adil192/saber#534] opened 2023-04-05 07:48 UTC
Good morning,
I can't login into my Nextcloud istance because I haven't the encryption active.
Is it possible add the possibility to login without file encryption password?

Regards,

**Comment by adil192** [comment] 2023-04-05 16:28
Duplicate of https://github.com/adil192/saber/issues/116

**Closed** 2023-04-05 16:29 UTC
Labels: duplicate, invalid, nextcloud help
