### ISSUE TITLE
Move images or selected lines between different pages.

### ISSUE THREAD

**Issue by GuiSousa135** [adil192/saber#719] opened 2023-06-17 14:47 UTC
### Motivation

Whenever we import an image, it always appears on the first page, without the possibility of moving to different pages, this also happens with lines or drawings, being restricted to moving the selection to another part of the note.

### Solution

Allow selected items to be moved between different pages without restrictions, this would make it possible to add images and then change between different parts of a note.

### Alternatives

Maybe the possibility to copy a selection and then paste elsewhere in the note (other page).

### Saber version

v0.13.0 F-Droid

### Device

- Device: Samsung Galaxy Tab s6 Lite
- OS: Android 12L

- Device: Samsung Galaxy S20 FE
- OS: Android 12

### Anything else?

![Screenshot_20230617-114616](https://github.com/adil192/saber/assets/55188286/aaccc79c-b637-4365-88df-067618e83482)

**Comment by adil192** [comment] 2023-06-17 18:25
Duplicate of #405

**Closed by adil192** 2023-06-17 18:25 UTC
Labels: enhancement
