### ISSUE TITLE
Several bugs / weird behaviors

### ISSUE THREAD

**Issue by FoilCan** [adil192/saber#215] opened 2023-01-09 11:07 UTC
**Describe the bug**
If found several bugs / IMO weird behaviors, so I decided to post them all here to avoid spamming. Can separate them if you think it's better that way.

I highlighted the bugs with numbers for better clarity.

- [ ] 1. The "pen resize" tool appears at the bottom even if toolbar is set to be positioned on top.
- [x] 2. The cursor stays displayed even after switching back to some other tool.
- [x] 3. When using the "text typing" tool, pressing space 2+ times gets dot added at the end of the word even if the word isn't capitalized.
- [x] 4. The "thickness adjustment" tool only adjusts thickness of the "pen" but it doesn't resize thickness of the "pencil" or whatever it is.

**To Reproduce**
1. Double click "pen" tool on the toolbar, while it is positioned on top.
2. When toggling on the "text typing" tool leave the cursor at the end of the last string and switch to some other tool.
3. Type any word using the "text typing" tool and press space 2+ times.
4. Double click the "pen" tool to toggle resizing, switch to the "pencil" tool and try resizing it.

**Expected behavior**
1. The pen resize tool should appear at the top.
2. The cursor should hide after switching to some other tool.
3. Auto-adding dot at the end of the word should be optional (option in settings).
4. The thickness adjustment should also adjust size of the "pencil".

**Screenshots**
![Screenshot_20230109-111853_Saber](https://user-images.githubusercontent.com/121516638/211289394-40df7ae6-8505-4a37-ab4d-415aa38321ed.png)

**Device (please complete the following information):**
 - Device: Galaxy Tab S6 lite
 - OS: Android 12 (Lineage OS)
 - Version: 19-20221204-microG-gta4xl

**Comment by adil192** [comment] 2023-01-09 17:25
1. It doesn't seem possible at the moment to move this to the top as its a Material Design [bottom sheet](https://m3.material.io/components/bottom-sheets/overview).
2. I can't reproduce this on my phone but hopefully this patch fixes it
3. This is a setting of your keyboard. If you use Gboard, you can turn this off in Text Correction > Double-space full stop
4.

**Comment by adil192** [comment] 2023-01-30 01:31
Do you still experience 2?

**Comment by FoilCan** [comment] 2023-01-30 22:36
> Do you still experience 2?

Yes, I do (v0.7.0).

**Comment by adil192** [comment] 2023-04-03 04:25
2 might be fixed by https://github.com/singerdmx/flutter-quill/pull/1152

**Closed as completed** 2023-04-03 16:17 UTC
Labels: bug
