### ISSUE TITLE
Ability to add/change Fonts of Notes(Not of app) 

### ISSUE THREAD

**Issue by sushreeisback** [adil192/saber#1071] opened 2023-12-22 11:06 UTC
### Motivation

 The one thing that's very important to me in any text editor that I work with is the ability to change fonts, It kills that creative force within me everytime I see the default wicked font inside the app you have choosen to work with. 
![SmartSelect_20231222-162904](https://github.com/saber-notes/saber/assets/78468711/9793c56b-8fb2-448d-8945-c5fe2b51d6a7)
 

### Solution

I want the ability to change/use my own font by uploading my font's otf/ttf font file. 

### Alternatives

A good alternative is to atleast upload some predefined fonts to choose from, if you can't grant us the ability to upload custom fonts. 
The fonts you can upload might include Helvetica, Times New Roman, Sans Serif, Arial, Courier, serif, calibri, futura , Didot, Garamond etc 

### Saber version

v0.18.5 F-Droid (18050 

### Device

- Device: Samsung Galaxy M31
- OS: Android 12

**Comment by adil192** [comment] 2023-12-22 17:05
Duplicate of #488.

**Closed as not planned by adil192** 2023-12-22 17:05 UTC
Labels: duplicate, enhancement
