### ISSUE TITLE
Selected text goes underneath the page

### ISSUE THREAD

**Issue by randomguyrantaro** [adil192/saber#784] opened 2023-07-08 09:46 UTC
### Describe the bug

When moving the text between pages, it goes underneath rather than staying on top of it.
![Screenshot_20230708-150845](https://github.com/adil192/saber/assets/136763244/7cd2ae71-4e1a-4519-8c9a-f7105c022142)

### To reproduce

1. Write something
2. Select it using the select tool
3. Try to drag it to a different page

### Expected behavior

The text should stay on top when dragged to a different page.

### Saber version

v 0.14.2 F-Droid

### Device

- Device:  Xiaomi Pad 6
- OS: Android 13

**Comment by adil192** [comment] 2023-07-09 19:02
Duplicate of https://github.com/adil192/saber/issues/405

**Closed by adil192** 2023-07-09 19:02 UTC
Labels: duplicate, enhancement
