### ISSUE TITLE
Is WebDAV/S3 synchronization possible?

### ISSUE THREAD

**Issue by Benjamin-Watson0** [adil192/saber#765] opened 2023-07-02 10:35 UTC
### Motivation

They are a common protocol. Compared with creating a new NextCloud network disk, it is more convenient and the cost is lower. (Storage cost of S3 is low)

### Solution

Is WebDAV/S3 synchronization possible?

### Saber version

0.14

### Device

- Device: vivo s7
- OS: Android 10

### Anything else?

Thank you for your selflessness.😊

**Comment by adil192** [comment] 2023-07-02 19:33
Duplicate of #201

**Closed by adil192** 2023-07-02 19:33 UTC
Labels: duplicate, enhancement
