### ISSUE TITLE
[FEAT] Custom Save Directories

### ISSUE THREAD

**Issue by WasteOfO2** [adil192/saber#521] opened 2023-04-01 14:01 UTC
### Motivation

I want to have a local backup of all my current notes, but I can't seem to find where Saber saves them on android.

I have seen somewhere that they are saved in the "document" folder in root somewhere, not sure.

### Solution

Allow the user to set the directory where Saber saves its notes, or atleast let the user have access to them in non-root directories, how other apps do.

### Alternatives

Change the default notes directory to `~/Android/data/com.adilhanney.saber/files`

### Saber version

v0.10.0

### Device

- Device: Samsung Galaxy Tab S6 Lite LTE
- OS: Lineage OS 19.1
- Browser (if applicable): -

### Anything else?

Directory in question

![Screenshot_20230401-193036_Files](https://user-images.githubusercontent.com/45941793/229293700-4954cc71-3a09-47bf-a8dd-7fe82f0d578c.png)

**Comment by adil192** [comment] 2023-04-01 14:05
Duplicate of #24

**Closed by adil192** 2023-04-01 14:05 UTC
Labels: enhancement

**Comment by RealVegOs** [comment] 2024-01-04 22:16
Please do not close this feature request! I also want to store locally. I do not need any cloud storage. There are not that much hand writing notes apps. There is only Butterfly, which is unusable for me for various reasons. Perhaps there are more similar apps on Google Play, but I will not install any of them, for privacy reasons. So Please! Don't be that harsh! THX!!!
