### ISSUE TITLE
Saber apps desynchronized

### ISSUE THREAD

**Issue by MisterCcobD** [adil192/saber#909] opened 2023-09-03 15:18 UTC
### Describe the bug

Desktop and Android apps show different state of notes, when i check on mobile, i see unchecked and on desktop i see checked.
Using Manjaro KDE on Lenovo Ideeapad and OnePlus 7 with OxygenOs 13
is just unsynched and i did log in a couple of times on each device and it shows is synching but never changes  a thing

### To reproduce

idk brah...is just unsynched and i did log in a couple of times on each device and it shows is synching but never changes  a thing

### Expected behavior

To sync

### Saber version

0.15.2 (15020)

### Device

- Device: IdeeaPad & OnePlus 7 (HD1900)
- OS: Manjaro KDE Linux & Oxygen Os 13

**Comment by adil192** [comment] 2023-09-04 17:07
Since this isn't reproducible, I'm going to have to close this issue

**Closed by adil192** 2023-09-04 17:07 UTC
Labels: bug
